//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShareApi.Models.Repositories.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int BookingID { get; set; }
        public int VehicleID { get; set; }
        public Nullable<int> TransactionID { get; set; }
        public int AccountID { get; set; }
        public string BookingStatus { get; set; }
        public System.DateTime CheckOut { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
    
        public virtual BookingStatus BookingStatu { get; set; }
        public virtual Car Car { get; set; }
        public virtual TransactionHistory TransactionHistory { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
