//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShareApi.Models.Repositories.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransactionHistory()
        {
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int TransactionID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string TransactionStatus { get; set; }
        public string Reference { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
    
        public virtual Booking Booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
        public virtual TransactionStatu TransactionStatu { get; set; }
    }
}
